### PR TITLE
refactoring and bug fixes

### PR DESCRIPTION
**Pull request by Rudxain**
I've been considering to add the same funcs, but for `byte`s instead. This would avoid the need to call `string()`

### CODE REVIEW

**Comment by hammamikhairi** [comment]
Since we mostly use the funcs to compare `byte`s, we can just change their args' types to `byte` and change to `string` when necessary.

**Review by hammamikhairi — CHANGES_REQUESTED** [review]
Change The arg types of `IsLower` & `IsUpper` to `byte` and apply the necessary changes in the `Encrypter/encrypter.go` file. (and thanks)

**Comment by Rudxain** [comment]
I'll convert some other fns to accept `byte`s

**Review by hammamikhairi — APPROVED** [review]
lgtm, thank you for the effort.

**Comment by Rudxain** [comment]
You're welcome :)

**Pull request merged**
