### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by OpenSourceSimon**

### CODE REVIEW

**Review by hammamikhairi — APPROVED** [review]
lgtm

**Comment by CattopyTheWeb** [comment]
@OpenSourceSimon that wasn't actually a typo

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon that wasn't actually a typo

It was a typo, 100% sure

**Comment by CattopyTheWeb** [comment]
Hmm, if you're sure

**Pull request merged**
